HAI 1.2

I HAS A VAR            BTW VAR є nullінетипізований
VAR
VAR R "THREE"          BTW VAR тепер YARN і дорівнює "THREE"
VAR R 3                BTW VAR2 тепер NUMBR і дорівнює 3
VAR R 3.14             BTW VAR2 тепер NUMBAR і дорівнює 3.14
VAR R WIN              BTW VAR2 тепер TROOF і дорівнює WIN
VAR R NOOB             BTW VAR2 тепер NOOB

I HAS A STR ITZ "Hello"  BTW правильно оголошення змінної
I HAS A NUM ITZ 10
I HAS A FLT ITZ 3.14
I HAS A BOOL ITZ WIN
I HAS A INPUTVAR

GIMMEH INPUTVAR

VISIBLE "Hello, world!"
VISIBLE INPUTVAR
VISIBLE "Var: " AN INPUTVAR
VISIBLE SMOOSH "Var: " AN INPUTVAR MKAY

SMOOSH "Hello" AN "World" MKAY
SMOOSH "SHello" AN " " AN INPUTVAR MKAY
VISIBLE IT

MAEK "123" A NUMBR
I HAS A STRVAL ITZ "456"
I HAS A NUMVAL ITZ MAEK STRVAL A NUMBR
I HAS A NUMVAL1 ITZ 789
I HAS A STRVAL1 ITZ MAEK NUMVAL1 A YARN
I HAS A STRVAL2 ITZ "WIN"
I HAS A BOOLVAL ITZ MAEK STRVAL2 A TROOF
I HAS A INTEGER ITZ 42
I HAS A FLOATVAL ITZ MAEK INTEGER A NUMBAR
I HAS A FLOATVAL1 ITZ 3.14
I HAS A INTEGER1 ITZ MAEK FLOATVAL1 A NUMBR

SUM OF 3 AN 5          BTW 3 + 5
SUM OF NUM AN 5        BTW 3 + 5
SUM OF NUM AN INTEGER1  BTW 3 + 5
SUM OF 3 AN 5          BTW 3 + 5
DIFF OF 10 AN 4        BTW 10 - 4
PRODUKT OF 6 AN 7      BTW 6 * 7
QUOSHUNT OF 20 AN 4    BTW 20 / 4
MOD OF 10 AN 3         BTW 10 % 3
BIGGR OF 4 AN 9        BTW max(4, 9)
SMALLR OF 4 AN 9       BTW min(4, 9)

BOTH OF WIN AN FAIL         BTW WIN iff x=WIN, y=WIN
EITHER OF WIN AN FAIL       BTW FAIL iff x=FAIL, y=FAIL
WON OF WIN AN FAIL          BTW FAIL iff x=y
NOT WIN                     BTW WIN iff x=FAIL
ALL OF WIN AN FAIL MKAY     BTW infinite arity AND
ANY OF WIN AN FAIL MKAY     BTW infinite arity OR

BOTH SAEM 3 AN 3            BTW WIN iff x == y
DIFFRINT 3 AN 4             BTW WIN iff x != y

BTW Example:
I HAS A NUM1 ITZ 10
I HAS A NUM2 ITZ 20
I HAS A BOOL1 ITZ BOTH SAEM NUM1 AN 10      BTW BOOL1 буде WIN, якщо NUM1 дорівнює 10
I HAS A BOOL2 ITZ DIFFRINT NUM2 AN 20       BTW BOOL2 буде FAIL, якщо NUM2 дорівнює 20
I HAS A RESULT1 ITZ BOTH OF BOOL1 AN BOOL2         BTW WIN iff BOOL1=WIN, BOOL2=WIN

BTW Example: без else if
O RLY?
  YA RLY
    VISIBLE "It is true!"
  NO WAI
    VISIBLE "It is false!"
OIC

BTW Example: з else if
I HAS A NUM0 ITZ 15
BOTH SAEM NUM0 AN 10
O RLY?
  YA RLY
    VISIBLE "NUM is 10"
  MEBBE BOTH SAEM NUM0 AN 15
    VISIBLE "NUM is 15"
  NO WAI
    VISIBLE "NUM is something else"
OIC

I HAS A STR0 ITZ "R"
STR0
WTF?
  OMG "R"
    VISIBLE "RED FISH"
    GTFO
  OMG "Y"
    VISIBLE "YELLOW FISH"
  OMGWTF
    VISIBLE "FISH IS TRANSPARENT"
OIC

IM IN YR LOOP
  VISIBLE "Looping..."
  GTFO
IM OUTTA YR LOOP

IM IN YR LOOP UPPIN YR VAR TIL BOTH SAEM VAR AN 10
  VISIBLE VAR
IM OUTTA YR LOOP

BTW Цикл в циклі
I HAS A COUNT ITZ 0
IM IN YR OUTERLOOP
  IM IN YR INNERLOOP
    VISIBLE "Outer loop count: " AN COUNT
    COUNT R SUM OF COUNT AN 1
    BOTH SAEM COUNT AN 3, GTFO
  IM OUTTA YR INNERLOOP
  VISIBLE "End of inner loop"
  GTFO
IM OUTTA YR OUTERLOOP

BTW Функція з двома аргументами
HOW IZ I FUNC YR ARG1 AN YR ARG2
  VISIBLE ARG1
  VISIBLE ARG2
IF U SAY SO

I IZ FUNC YR "Hello" AN YR "World" MKAY

BTW Функція з поверненням значення
HOW IZ I ADD YR A1 AN YR B
  FOUND YR SUM OF A1 AN B
IF U SAY SO

I HAS A RESULT ITZ I IZ ADD YR 5 AN YR 10 MKAY
VISIBLE RESULT

HOW IZ I ADD1 YR A1 AN YR B
  I HAS A RESULT ITZ SUM OF A1 AN B
  FOUND YR RESULT
IF U SAY SO

I HAS A RESULT0 ITZ I IZ ADD1 YR 5 AN YR 10 MKAY
VISIBLE RESULT0

BTW Вкладені функції
HOW IZ I FUNC2 YR ARG2
  VISIBLE ARG2
IF U SAY SO

HOW IZ I FUNC1 YR ARG1
  VISIBLE ARG1
  I IZ FUNC2 YR "Inner call" MKAY
IF U SAY SO

I IZ FUNC1 YR "Outer call" MKAY

OBTW this is a long comment block
                 see, i have more comments here
                 and here
TLDR

I HAS A VARR, VARR R 10, VISIBLE VARR

KTHXBYE

